# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e149dd8a39e070b13ffa1aeb6b96509d45248469905970a5df6200aa067d1bd9265a349c26044bead2c807451d819cf55cd56a0c5dab7c71ed38851c69307de

test:
  secret_key_base: 10b2a34a84f8166fb17d6a111f932429d1b77660d9e155af6dbce260b63bb1e60f0c749fed8254db75ecf3ad2730d8ec216c72f0485873e6d427925dce24c01b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
